//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalidadSoftware.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Databases : DbContext
    {
        public Databases()
            : base("name=Databases")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<Categoria_Empleado> Categoria_Empleado { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Bonificacion> Bonificacion { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<Valor_Hora> Valor_Hora { get; set; }
    }
}
