//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalidadSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int rut_empleado { get; set; }
        public string dv_rut { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string genero { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public string email { get; set; }
        public int telefono { get; set; }
        public string direccion { get; set; }
        public string profesion { get; set; }
        public int experiencia { get; set; }
        public Nullable<int> id_user { get; set; }
        public byte[] foto { get; set; }
    
        public virtual users users { get; set; }
    }
}
