//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalidadSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor_Hora
    {
        public int id_empleado { get; set; }
        public System.DateTime fecha_calculo { get; set; }
        public int valor_hora1 { get; set; }
        public int horas_trabajadas { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
